defaults:
  - base.yaml

net:
  _target_: src.models.modules.swin_3d.SwinUnet3D
  img_size: 224
  patch_size: 4
  in_channels: 3
  num_frames: 4
  tubelet_size: 1
  num_classes: 2
  embed_dim: 96
  depths: [2, 4, 6, 4]
  num_heads: [3, 8, 12, 24]
  window_size: [1, 8, 8]
  input_format: "NCHW"
  mlp_ratio: 4.0
  qkv_bias: true
  drop_rate: 0.0
  proj_drop_rate: 0.0
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  patch_norm: true
  norm_layer:
    _target_: torch.nn.LayerNorm
    _partial_: true
  weight_init: ""
optimizer:
  lr: 5e-4
  