defaults:
  - base.yaml
  - override criterion: mse
  - override optimizer: adamw

_target_: src.models.mae_module.MAEModule
net:
  _target_: src.models.modules.encoders.swin_mae.TSwinMAE
  img_size: 224
  patch_size: 4
  in_channels: 3
  embed_dim: 96
  depths: [2, 4, 6, 4]
  num_heads: [3, 8, 12, 24]
  window_size: 8
  mask_ratio: 0.75
  mlp_ratio: 4.0
  qkv_bias: true
  drop_rate: 0.0
  proj_drop_rate: 0.0
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  patch_norm: true
  norm_layer:
    _target_: torch.nn.LayerNorm
    _partial_: true
  weight_init: ""
optimizer:
  lr: 5e-4
  