defaults:
  - model_checkpoint
  - early_stopping
  - rich_model_summary
  - rich_progress_bar
  - log_batch_images

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: ${optimized_metric}
  mode: "max"
  save_last: true
  auto_insert_metric_name: false

early_stopping:
 monitor: ${optimized_metric}
 patience: 100
 mode: "max"

rich_model_summary:
  max_depth: -1
