# @package _global_

defaults:
  - _self_
  - callbacks:
    - rich_progress_bar
    - log_batch_images
  - data: null
  - model: null
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - plugins: default.yaml
  - trainer: null

  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  - experiment: null

  - optional local: default.yaml
  - debug: null

trainer:
  log_every_n_steps: 1 # log minimum of number of shots

experiment_name: null
experiment_description: "A simple template to train a model with PyTorch Lightning"
task_name: "train"
tags:
  mode: "dev"
  stage: ${task_name}
  dataset: null
  model: ${model.net._target_}
  description: null # not the same as experiment_description, this is relative to the run
  version: "0.1"

optimized_metric: "val/acc"
k_shots: [1, 5, 10, 20]
pretrained_model: null
ckpt_path: null
seed: 42
